title = ""
baseURL = "https://www.sigsum.org/"
theme = "researcher"

[params]
  author = "The Sigsum Project"
  description = "The Sigsum Project website"
  favicon = "/media/avatar.ico"
  logo = "/media/logo.svg"
  [params.footer]
    text = "er3n3jnvoyj2t37yngvzr35b6f4ch5mgzl3i6qlkvyhzmaxo62nlqmqd.onion"
    url = "http://er3n3jnvoyj2t37yngvzr35b6f4ch5mgzl3i6qlkvyhzmaxo62nlqmqd.onion/"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Outfit"
    pageWidth = "750px"
    avatarSize = "90px"
  [[params.socialIcons]]
    icon = "fab fa-git"
    title = "git"
    url = "https://git.sigsum.org/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "https://lists.sigsum.org/"

[menu]
  [[menu.main]]
    name = "Docs"
    url = "/docs"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true # allow raw HTML in markdown files
